[logging]
debug = true

[inference]
together = [
    "meta-llama/Llama-3.3-70B-Instruct-Turbo",
    "Qwen/Qwen2.5-72B-Instruct-Turbo",
    "Qwen/Qwen2.5-Coder-32B-Instruct",
    "microsoft/WizardLM-2-8x22B",
]
azure = [
    "azure",
]
vllm = [
    "Qwen/Qwen2.5-1.5B-Instruct",
    "meta-llama/Llama-3.2-1B",
    "google/gemma-3-1b-it",
    "alpindale/WizardLM-2-8x22B",
    "Qwen/Qwen1.5-72B-Chat",
    "meta-llama/Llama-3.1-8B-Instruct",
    "Alibaba-NLP/gte-Qwen2-7B-instruct",
    "Qwen/QwQ-32B",
    "deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct",
    "Qwen/Qwen2-Math-7B-Instruct",
    "Qwen/Qwen2-7B-Instruct",
    "wzhouad/gemma-2-9b-it-WPO-HB",
    "Qwen/Qwen2.5-0.5B",
    "Qwen/Qwen2.5-0.5B-Instruct",
    "Qwen/Qwen1.5-0.5B-Chat",
    "meta-llama/Llama-3.2-1B-Instruct",
    "Qwen/Qwen3-4B",
    "Qwen/Qwen3-1.7B",
    "Qwen/Qwen3-0.6B",
]
openrouter = [
    "qwen/qwen3-30b-a3b",
    "qwen/qwen3-14b",
]

[inference.vllm_hosts]
"Qwen/Qwen2.5-1.5B-Instruct" = "localhost"
"meta-llama/Llama-3.2-1B" = "localhost"
"google/gemma-3-1b-it" = "localhost"
"alpindale/WizardLM-2-8x22B" = "localhost"
"Qwen/Qwen1.5-72B-Chat" = "localhost"
"meta-llama/Llama-3.1-8B-Instruct" = "localhost"
"Alibaba-NLP/gte-Qwen2-7B-instruct" = "localhost"
"Qwen/QwQ-32B" = "localhost"
"deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct" = "localhost"
"Qwen/Qwen2-Math-7B-Instruct" = "localhost"
"Qwen/Qwen2-7B-Instruct" = "localhost"
"wzhouad/gemma-2-9b-it-WPO-HB" = "localhost"
"Qwen/Qwen2.5-0.5B" = "localhost"
"Qwen/Qwen2.5-0.5B-Instruct" = "localhost"
"Qwen/Qwen1.5-0.5B-Chat" = "localhost"
"meta-llama/Llama-3.2-1B-Instruct" = "localhost"
"Qwen/Qwen3-4B" = "localhost"
"Qwen/Qwen3-1.7B" = "localhost"
"Qwen/Qwen3-0.6B" = "localhost"

[inference.vllm_ports]
"Qwen/Qwen2.5-1.5B-Instruct" = 18000
"meta-llama/Llama-3.2-1B" = 18001
"google/gemma-3-1b-it" = 18002
"alpindale/WizardLM-2-8x22B" = 18003
"Qwen/Qwen1.5-72B-Chat" = 18004
"meta-llama/Llama-3.1-8B-Instruct" = 18005
"Alibaba-NLP/gte-Qwen2-7B-instruct" = 18006
"Qwen/QwQ-32B" = 18007
"deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct" = 18008
"Qwen/Qwen2-Math-7B-Instruct" = 18009
"Qwen/Qwen2-7B-Instruct" = 18010
"wzhouad/gemma-2-9b-it-WPO-HB" = 18011
"Qwen/Qwen2.5-0.5B" = 18012
"Qwen/Qwen2.5-0.5B-Instruct" = 18013
"Qwen/Qwen1.5-0.5B-Chat" = 18014
"meta-llama/Llama-3.2-1B-Instruct" = 18015
"Qwen/Qwen3-4B" = 18016
"Qwen/Qwen3-1.7B" = 18017
"Qwen/Qwen3-0.6B" = 18018

[inference.openrouter_providers]
"qwen/qwen3-30b-a3b" = ["novita/fp8"]
"qwen/qwen3-14b" = ["deepinfra/fp8"]
