[logging]
debug = true

[inference]
together = [
    "meta-llama/Llama-3.3-70B-Instruct-Turbo",
    "Qwen/Qwen2.5-72B-Instruct-Turbo",
    "Qwen/Qwen2.5-Coder-32B-Instruct",
    "microsoft/WizardLM-2-8x22B",
]
azure = [
    "azure",
]
vllm = [
    "Qwen/Qwen2.5-1.5B-Instruct",
    "meta-llama/Llama-3.2-1B",
    "google/gemma-3-1b-it",


    "meta-llama/Llama-3.1-8B-Instruct",
    "Alibaba-NLP/gte-Qwen2-7B-instruct",
]

[inference.vllm_hosts]
"Qwen/Qwen2.5-1.5B-Instruct" = "localhost"
"meta-llama/Llama-3.2-1B" = "localhost"
"google/gemma-3-1b-it" = "localhost"


"meta-llama/Llama-3.1-8B-Instruct" = "localhost"
"Alibaba-NLP/gte-Qwen2-7B-instruct" = "localhost"

[inference.vllm_ports]
"Qwen/Qwen2.5-1.5B-Instruct" = 18000
"meta-llama/Llama-3.2-1B" = 18001
"google/gemma-3-1b-it" = 18002


"meta-llama/Llama-3.1-8B-Instruct" = 18005
"Alibaba-NLP/gte-Qwen2-7B-instruct" = 18006
